# Generated by Django 4.2 on 2024-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
