# Generated by Django 4.2 on 2024-01-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
    ]
